name: astra
channels:
dependencies:
  - python=3.7
  - requests
  - pip
  # Commons.
  - numpy 
  - astropy
  - scipy
  - matplotlib
  - ipython
  - click>=7.0
  - pyyaml>=5.1  
  - pip: # Even though this won't be used for local installations that don't have modules.
    - "--editable=git+https://github.com/sdss/sdss_install.git@master#egg=sdss_install"
    - "--editable=git+https://github.com/sdss/astra.git@master#egg=astra"
