name: astra
dependencies:
    - numpy
    - scipy
    - astropy==5.1
    - tqdm
    - pip
    - pyyaml
    - cryptography==3.4.8 # see https://github.com/sdss/astra/wiki/GLIBC_2.28-not-found
    - protobuf==3.20.1 # for airflow warnings
    - pip:
      - healpy
      - PyYAML
      - sdss-access
      - sdssdb
      - sdsstools
      - specutils
      - apache-airflow[async,postgres,google,http]==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-3.8.txt
